---
title: "PSEATE - Relations entre latitudes/longitudes et dosages"
subtitle: ""
output:
  html_document:
    toc: true
    number_sections: true
    toc_float: true
---

```{r, include = F}
# Output figure in HTML5
if (knitr::is_html_output()) knitr::knit_hooks$set(
  plot = function(x, options) {
    cap  <- options$fig.cap  # figure caption
    tags <- htmltools::tags
    as.character(tags$figure(
      tags$img(src = x, alt = cap),
      tags$figcaption(cap)
    ))
  }
)

# packages
source("C:/Users/ccjuhasz/Desktop/SMAC/GITHUB/SMAC-ENTROPIE_tracking/PTEBAR-JUV/packages_list.r")
library(knitr)

iso <- read.table("C:/Users/ccjuhasz/Desktop/SMAC/Projet_publi/6-PNB_isotopes/DATA/PNB_SI_HG_GLS_centroide.txt",
                      sep = "\t",
                      dec = ".",
                      h = TRUE)
models_lat <- readRDS("C:/Users/ccjuhasz/Desktop/SMAC/Projet_publi/6-PNB_isotopes/DATA/GitHub_Pages/ISOSCAPE_lm_LAT_vs_HG_C_N.rds")
models_lon <- readRDS("C:/Users/ccjuhasz/Desktop/SMAC/Projet_publi/6-PNB_isotopes/DATA/GitHub_Pages/ISOSCAPE_lm_LON_vs_HG_C_N.rds")

glob_pred_lat <- readRDS("C:/Users/ccjuhasz/Desktop/SMAC/Projet_publi/6-PNB_isotopes/DATA/GitHub_Pages/ISOSCAPE_pred_LAT_vs_HG_C_N.rds")
glob_pred_lon <- readRDS("C:/Users/ccjuhasz/Desktop/SMAC/Projet_publi/6-PNB_isotopes/DATA/GitHub_Pages/ISOSCAPE_pred_LON_vs_HG_C_N.rds")
```


# Latitudes des centroides des kernels 50  

## Mercure vs Latitudes

```{r, echo = F}
plot(iso$CENTRO_LAT,
     iso$HG_MEAN,
     xlab = "Latitude",
     ylab = "Mean Hg",
     bty = "n")

lines(glob_pred_lat$lat,
      glob_pred_lat$fit_hg,
      col = "red")
lines(glob_pred_lat$lat,
      glob_pred_lat$fit_hg - glob_pred_lat$se_fit_hg,
      col = "red",
      lty = 4)
lines(glob_pred_lat$lat,
      glob_pred_lat$fit_hg + glob_pred_lat$se_fit_hg,
      col = "red",
      lty = 4)

summary(models_lat[[1]])
```

## Carbone vs Latitude

```{r, echo = F}
plot(iso$CENTRO_LAT,
     iso$d13C_MEAN,
     xlab = "Latitude",
     ylab = "Mean d13C",
     bty = "n")

lines(glob_pred_lat$lat,
      glob_pred_lat$fit_13c,
      col = "red")
lines(glob_pred_lat$lat,
      glob_pred_lat$fit_13c - glob_pred_lat$se_fit_13c,
      col = "red",
      lty = 4)
lines(glob_pred_lat$lat,
      glob_pred_lat$fit_13c + glob_pred_lat$se_fit_13c,
      col = "red",
      lty = 4)

summary(models_lat[[2]])
```
## Azote vs Latitude

```{r, echo = F}
plot(iso$CENTRO_LAT,
     iso$d15N_MEAN,
     xlab = "Latitude",
     ylab = "Mean d15N",
     bty = "n")

lines(glob_pred_lat$lat,
      glob_pred_lat$fit_15n,
      col = "red")
lines(glob_pred_lat$lat,
      glob_pred_lat$fit_15n - glob_pred_lat$se_fit_15n,
      col = "red",
      lty = 4)
lines(glob_pred_lat$lat,
      glob_pred_lat$fit_15n + glob_pred_lat$se_fit_15n,
      col = "red",
      lty = 4)

summary(models_lat[[3]])
```



# Longitudes des centroides des kernels 50  

## Mercure vs Longitudes

```{r, echo = F}
plot(iso$CENTRO_LON,
     iso$HG_MEAN,
     xlab = "Longitude",
     ylab = "Mean Hg",
     bty = "n")

lines(glob_pred_lon$lon,
      glob_pred_lon$fit_hg,
      col = "red")
lines(glob_pred_lon$lon,
      glob_pred_lon$fit_hg - glob_pred_lon$se_fit_hg,
      col = "red",
      lty = 4)
lines(glob_pred_lon$lon,
      glob_pred_lon$fit_hg + glob_pred_lon$se_fit_hg,
      col = "red",
      lty = 4)

summary(models_lon[[1]])
```

## Carbone vs Longitudes

```{r, echo = F}
plot(iso$CENTRO_LON,
     iso$d13C_MEAN,
     xlab = "Longitude",
     ylab = "Mean d13C",
     bty = "n")

lines(glob_pred_lon$lon,
      glob_pred_lon$fit_13c,
      col = "red")
lines(glob_pred_lon$lon,
      glob_pred_lon$fit_13c - glob_pred_lon$se_fit_13c,
      col = "red",
      lty = 4)
lines(glob_pred_lon$lon,
      glob_pred_lon$fit_13c + glob_pred_lon$se_fit_13c,
      col = "red",
      lty = 4)

summary(models_lon[[2]])
```
## Azote vs Longitudes

```{r, echo = F}
plot(iso$CENTRO_LON,
     iso$d15N_MEAN,
     xlab = "longitude",
     ylab = "Mean d15N",
     bty = "n")

lines(glob_pred_lon$lon,
      glob_pred_lon$fit_15n,
      col = "red")
lines(glob_pred_lon$lon,
      glob_pred_lon$fit_15n - glob_pred_lon$se_fit_15n,
      col = "red",
      lty = 4)
lines(glob_pred_lon$lon,
      glob_pred_lon$fit_15n + glob_pred_lon$se_fit_15n,
      col = "red",
      lty = 4)

summary(models_lon[[3]])
```
