---
title: "PSEATE - Localisations repro vs migration"
subtitle: "Exploration des données"
output:
  html_document:
    toc: true
    number_sections: true
    toc_float: true
---

```{r, include = F}
# Output figure in HTML5
if (knitr::is_html_output()) knitr::knit_hooks$set(
  plot = function(x, options) {
    cap  <- options$fig.cap  # figure caption
    tags <- htmltools::tags
    as.character(tags$figure(
      tags$img(src = x, alt = cap),
      tags$figcaption(cap)
    ))
  }
)

# packages
source("C:/Users/ccjuhasz/Desktop/SMAC/GITHUB/SMAC-ENTROPIE_tracking/PTEBAR-JUV/packages_list.r")

synth <- readRDS("C:/Users/ccjuhasz/Desktop/SMAC/Projet_publi/6-PNB_isotopes/DATA/GitHub_Pages/ISOSCAPE_synthese_par_ind.rds")

```

# Mise en contexte
  
## A développer
  
```{r}
knitr::kable(synth,
             caption = "Tab. 1. Synthèse de l'information spatiale par individu. La distance est exprimée en km.",
             row.names = F)
```
# Bilan data brutes  
   
```{r setup, include = FALSE}
pseate <- readRDS("C:/Users/ccjuhasz/Desktop/SMAC/Projet_publi/6-PNB_isotopes/DATA/GitHub_Pages/PSEATE_trips.rds")

pseate <- pseate[pseate$ID != "PNB-C2143", ]

pseate_sf <- st_as_sf(pseate,
                      coords = c("LON", "LAT"),
                      crs = 4326)

ll <- split(pseate_sf,
            pseate_sf$TYPE)

ll2 <- split(pseate_sf,
             pseate_sf$ID)

kern <- readRDS("C:/Users/ccjuhasz/Desktop/SMAC/Projet_publi/6-PNB_isotopes/DATA/GitHub_Pages/kernel50-90.rds")

ker50 <- lapply(kern, function(x) {x[[1]]})
ker90 <- lapply(kern, function(x) {x[[2]]})

iso <- read.table("C:/Users/ccjuhasz/Desktop/SMAC/Projet_publi/6-PNB_isotopes/DATA/PNB_ISOTOPES_locs_in_kernels_dates_SST.txt",
                  sep = "\t",
                  dec = ".",
                  h = TRUE)
iso_sf <- sf::st_as_sf(iso,
                       coords = c("CENTRO_LON", "CENTRO_LAT"),
                       crs = 4326)

library(knitr)
```

```{r, echo = F}
mapview(ll,
        col.region = c("#a9a9a976", "#000000a7"))


rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")

kable(rg2,
      row.names = T,
      caption = "Tab. 1.")

```

# Visualisation individuelle  

## C2127  
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2127"]],
            ll2[["PNB-C2127"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2127", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2127"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2127"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 2.')
```
## C2127_2019  
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2127_2019"]],
            ll2[["PNB-C2127_2019"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2127_2019", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2127_2019"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2127_2019"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 3.')
```
## C2128  
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2128"]],
            ll2[["PNB-C2128"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2128", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2128"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2128"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 4.')
```
## C2130  
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2130"]],
            ll2[["PNB-C2130"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2130", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2130"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2130"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 5.')
```
## C2133   
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2133"]],
            ll2[["PNB-C2133"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2133", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2133"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2133"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 6.')
```
## C2133_2019
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2133_2019"]],
            ll2[["PNB-C2133_2019"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2133_2019", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2133_2019"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2133_2019"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 7.')
```
## C2134  
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2134"]],
            ll2[["PNB-C2134"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2134", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2134"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2134"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 8.')
```
## C2135  
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2135"]],
            ll2[["PNB-C2135"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2135", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2135"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2135"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 9.')
```
## C2136  
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2136"]],
            ll2[["PNB-C2136"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2136", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2136"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2136"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 10.')
```
## C2137  
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2137"]],
            ll2[["PNB-C2137"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2137", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2137"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2137"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 11.')
```
## C2137_2019  
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2137_2019"]],
            ll2[["PNB-C2137_2019"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2137_2019", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2137_2019"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2137_2019"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 12.')
```
## C2138  
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2138"]],
            ll2[["PNB-C2138"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2138", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2138"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2138"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 13.')
```
## C2139  
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2139"]],
            ll2[["PNB-C2139"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2139", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2139"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2139"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 14.')
```
## C2141  
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2141"]],
            ll2[["PNB-C2141"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2141", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2141"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2141"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 15.')
```
## C2141_2019  
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2141_2019"]],
            ll2[["PNB-C2141_2019"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2141_2019", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2141_2019"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2141_2019"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 16.')
```
## C2142  
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2142"]],
            ll2[["PNB-C2142"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2142", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2142"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2142"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 17.')
```
## C2142_2019  
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2142_2019"]],
            ll2[["PNB-C2142_2019"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2142_2019", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2142_2019"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2142_2019"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 18.')
```
## C2144  
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2144"]],
            ll2[["PNB-C2144"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2144", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2144"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2144"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 19.')
```
## C2145  
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2145"]],
            ll2[["PNB-C2145"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2145", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2145"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2145"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 20.')
```
## C2859_2019  
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2859_2019"]],
            ll2[["PNB-C2859_2019"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2859_2019", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2859_2019"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2859_2019"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 21.')
```
## C2860_2019  
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2860_2019"]],
            ll2[["PNB-C2860_2019"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2860_2019", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2860_2019"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2860_2019"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 22.')
```
## C2866_2019  
```{r, echo = F}
ll1 <- split(ll2[["PNB-C2866_2019"]],
            ll2[["PNB-C2866_2019"]]$TYPE)

mapview(ll1,
        col.region = c("#a9a9a976", "#000000a7")) +
  mapview(iso_sf[iso_sf$ID == "PNB-C2866_2019", ],
          col.region = "red",
          layer.name = "centroïde") +
  mapview(ker90[["PNB-C2866_2019"]],
          layer.name = "kernel 90",
          col.region = "#8acef2") +
  mapview(ker50[["PNB-C2866_2019"]],
          layer.name = "kernel 50",
          col.region = "#009bed")

rg <- lapply(ll,
             function(x) {
               date_min <- min(x$DATE)
               date_max <- max(x$DATE)
               n_loc <- nrow(x)
               
               dt <- data.frame(min_date = date_min,
                                   max_date = date_max,
                                   loc_number = n_loc)
               dt
                             })
rg2 <- do.call("rbind", rg)
row.names(rg2) <- c("MIGRATION", "REPRODUCTION")
kable(rg2,
      row.names = T,
      caption = 'Tab. 23.')
```
