---
title: "PTEBAR - At-sea tracking"
subtitle: "Data exploration - Hour range"
output:
  html_document:
    toc: true
    number_sections: true
    toc_float: true
---

```{r, include = F}
if (knitr::is_html_output()) knitr::knit_hooks$set(
  plot = function(x, options) {
    cap  <- options$fig.cap  # figure caption
    tags <- htmltools::tags
    as.character(tags$figure(
      tags$img(src = x, alt = cap),
      tags$figcaption(cap)
    ))
  }
)

# packages
require(knitr)
require(mapview)
require(tidyverse)
require(sf)
require(adehabitatLT)
require(lubridate)
require(htmltools)
require(plotly)

source('C:/Users/Etudiant/Desktop/SMAC/GITHUB/SMAC-ENTROPIE_tracking/PTEBAR/PTEBAR_0-Functions_for_scripts.R')
```
# Fréquence d'acquisition de positions par jour  
  
  
```{r, include = F}
# source('C:/Users/Etudiant/Desktop/SMAC/GITHUB/SMAC-ENTROPIE_tracking/PTEBAR/PTEBAR_0-Functions_for_scripts.R')

gps <- read.table("C:/Users/Etudiant/Desktop/SMAC/Projet_publi/4-PTEBAR_GPS/DATA/PTEBAR_GPS_DB_V2_adehabLT.txt", h = T, sep = '\t', dec = ".") # Non duplicated data with NAs in lat/Long

# Conversion of dates
# gps$time <- as.POSIXct(strptime(as.character(gps$time),
#                                 '%Y-%m-%d %H:%M:%S'),
#                        tz = 'Indian/Mauritius')
# head(gps$time)
# class(gps$time)

gps$time <- strptime(paste(gps$time), "%Y-%m-%d %H:%M:%S")
gps$time <- as.character(gps$time)

gps$time <- as.POSIXct(gps$time, tz="Indian/Mauritius") 

```

```{r, echo = F}

gps_list <- split(gps, gps$Logger_ID)
freq_list <- lapply(gps_list, fix_freq,
                        date_min = min(gps$time),
                        date_max = max(gps$time))

```
```{r, echo = F}
l <- tagList()
for(i in 1:length(freq_list)){
  l[[i]] <- barp_fix_freq(freq_list[[i]], use_NA = T)
}
l
```

```{r, echo = F}
hour_seq <- data.frame(hour = seq(0, 23, 1), Freq = 0)
hour_freq_list <- list()
for (i in 1:length(gps_list)){
  hf <- data.frame(table(hour(gps_list[[i]]$time)))
  names(hf)[1] <- 'hour'
  hf$hour <- as.numeric(hf$hour)
  
  hour_freq_list[[i]] <- rbind(hf, hour_seq[!(hour_seq$hour %in% hf$hour),])
  names(hour_freq_list)[i] <- unique(gps_list[[i]]$Logger_ID)
}
```
# Fréquence d'acquisition de positions par heure  
  
```{r, echo = F}
l2 <- tagList()
for(i in 1:length(hour_freq_list)){
  
  fig <- plot_ly(hour_freq_list[[i]],
                 x = ~hour,
                 y = ~Freq,
                 type = 'bar',
                 name = '') 
  fig <- fig %>% layout(title = list(text = names(hour_freq_list)[i]))

  l2[[i]] <- fig
}

l2
```