---
title: "PTEBAR-JUV - Data explo"
author: "CCJ"
output:
  html_document:
    toc: true
    number_sections: true
    toc_float: true
---

```{r, include = F}
# Output figure in HTML5
if (knitr::is_html_output()) knitr::knit_hooks$set(
  plot = function(x, options) {
    cap  <- options$fig.cap  # figure caption
    tags <- htmltools::tags
    as.character(tags$figure(
      tags$img(src = x, alt = cap),
      tags$figcaption(cap)
    ))
  }
)

# packages
require(knitr)
require(mapview)
require(leafpop)
require(tidyverse)
require(dplyr)
require(sf)
require(lubridate)
```

```{css, echo = F}
.badCode {
background-color: red;
}

.goodCode {
  background-color: green;
}

.striped tbody tr:nth-children(even) {
  font-style: italic;
}
```

# Point méthodo  
 
```{r, echo = F}
tabb <- readRDS("C:/Users/ccjuhasz/Desktop/SMAC/Projet_publi/X-PTEBAR_argos_JUV/DATA/PTEBAR_JUV_Infos_bilan.rds")

tabb1 <- as.data.frame(tabb[, c('Vessel', 'start', 'deploy', 'n_loc', 'attach', 'burrow', 'ring', 'weight', 'wing', 'remark')])[, -11]

kable(tabb1, align = 'ccccccccc')
```

# Résumé des données argos
```{r, echo = F, class.source = 'test'}
tabb2 <- as.data.frame(tabb[, c('Vessel', 'max_date', 'min_lat', 'max_lat', 'min_lon', 'max_lon', 'max_speed', 'max_dist_km', 'date_loc', 'timing_for_max', 'dist_travel_km', 'duration_trip_day')])[, -13]

tabb2$duration_trip_day <- as.numeric(tabb2$duration_trip_day)
tabb2$timing_for_max <- as.numeric(tabb2$timing_for_max)
tabb2$max_date <- date(tabb2$max_date)
tabb2$date_loc <- date(tabb2$date_loc)


kable(tabb2
      , digits = 2
      , col.names = c('Device', 'Date max', 'Lat min', 'Lat max', 'Lon min', 'Lon max', 'Speed max', 'Dist max', 'Date dist max', 'Nb jr pour max loc', 'Dist tot', 'Duree trajet')
      # align = 'cccccccccccc'
      # , table.attr = 'class=\"striped\"'
      # , format = 'html'
      )
```
# Visualisation des trajets  
  
## Déploiement en 2017  
  
```{r, echo=F}

# map_lines <- readRDS("C:/Users/ccjuhasz/Desktop/SMAC/Projet_publi/X-PTEBAR_argos_JUV/DATA/PTEBAR_JUV_raw_map_lines.rds")
# 
# map_lines

tabb3 <- dplyr::left_join(tabb[, c('Vessel', 'min_date', 'geometry')], tabb2, by = 'Vessel')

# Round numerical values
tabb4 <- cbind(tabb3[, c(1:4, 11)], apply(as.data.frame(tabb3[,c( 'min_lat', 'max_lat', 'min_lon', 'max_lon', 'max_speed', 'max_dist_km', 'timing_for_max', 'dist_travel_km', 'duration_trip_day')])[, -10], 2, round, digit = 2))



tabb4$popup_info <- paste0("<b>PTT</b> ",
                                 tabb4$Vessel,
                                 "<br/>",
                                 "<b>Durée de l'enregistrement </b>",
                                 tabb4$duration_trip_day, " jours",
                                 "<br/>",
                                 "<b>Range latitude [</b>", tabb4$min_lat, "; ", tabb4$max_lat, "<b>]</b>",
                                 "<br/>",
                                 "<b>Range longitude [</b>", tabb4$min_lon, "; ", tabb4$max_lon, "<b>]</b>",
                           "</br>",
                           "<b>Vitesse maximale atteinte </b>", tabb4$max_speed, " unité ?",
                           "</br>",
                           "<b>Distance maximale à la colonie </b>", tabb4$max_dist_km, " atteint km en ", tabb4$timing_for_max, " jours",
                           "</br>",
                           "<b>Distance totale parcourue </b>", tabb4$dist_travel_km, " km")

  mapview(tabb4[year(tabb4$min_date) == 2017,],
          zcol = 'Vessel',
          burst = T,
          homebutton = F,
          popup = popupTable(tabb4[year(tabb4$min_date) == 2017,],
                             zcol = 'popup_info',
                             feature.id = FALSE,
                             row.numbers = FALSE,
                             className = 'mapview-popup'))
```  
  
## Déploiement en 2018  
  
```{r, echo=F}
    mapview(tabb4[year(tabb4$min_date) == 2018,],
          zcol = 'Vessel',
          burst = T,
          homebutton = F,
          popup = popupTable(tabb4[year(tabb4$min_date) == 2018,],
                             zcol = 'popup_info',
                             feature.id = FALSE,
                             row.numbers = FALSE,
                             className = 'mapview-popup'))

# in_run <- readRDS("C:/Users/ccjuhasz/Desktop/SMAC/Projet_publi/X-PTEBAR_argos_JUV/DATA/PTEBAR_JUV_in_Run_points_data.rds")
#   
#   mapview(in_run,
#           zcol = 'Vessel',
#           burst = T,
#           homebutton = F)

```